server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # FacturaScripts usa su index.php en la raíz con rewrite
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass apitest_fs_php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Bloquear acceso a archivos sensibles
    location ~ /\. {
        deny all;
    }
}
